### ISSUE TITLE
Compute Nodes

### ISSUE THREAD

**Issue by carlosperezepfl** [kvaps/kubernetes-in-kubernetes#2]
When the cluster is deployed, how do you add resources (compute nodes)? 
kube-dns is stuck waiting for resources with "no nodes available to schedule pods"

**Comment by kvaps** [comment]
Hi, thanks for interest!
Currently I'm working on new [kubefarm](https://github.com/kvaps/kubefarm) project which uses kubernetes-in-kubernetes and enables node provisioning for it over PXE.
@egeneralov also was thinking to prepare ansible backend for it.

Unfortunately, both implementations are not finished yet, but already now, you can expose kubernetes-in-kubernetes using standard Kubernetes service with `nodePort` or `loadBalancer` and join nodes using standard kubeadm binary.

By the way do not forget to fill up the certSANs information, otherwise kubelet and kubectls will refuse the SSL connection 
https://github.com/kvaps/kubernetes-in-kubernetes/blob/10ccfb25a67c5a11cff67a984df4efbbdb937371/deploy/helm/kubernetes/values.yaml#L55-L57

**Comment by carlosperezepfl** [comment]
Thanks for the reply, I will follow the project on your repo and see the evolution.
We can close the issue for the moment and will open a new one later if needed.
